### ISSUE TITLE
Where is the main.py? 

### ISSUE THREAD

**Issue by River-mao** [RogerQi/pascal-5i#1]
Thanks a lot, but I can't find the main.py file.

**Comment by plutonium-239** [comment]
Hey @River-mao! There is not supposed to be any main.py, it is supposed to be used like a dataset to a dataloader:

```py
from pascal_5i_reader import Pascal5iReader
from torch.utils.data import DataLoader

dataset = Pascal5iReader(root = "../data/", fold=0, train=True)
trainloader = DataLoader(dataset, batch_size=4, pin_memory=True, num_workers=4) # use num_workers = 0 on windows

for i, (imgs, labels) in enumerate(trainloader):
    # training
```

**Comment by RogerQi** [comment]
Sorry that your comment @River-mao got lost in mass amount of emails. This repo is intended to be used like a dataset for data loader - I can perhaps add a main.py/example.py to demonstrate how it is used.

Edited: I just noticed that I already included an example.ipynb in the repo. You should refer to that for sample usage.
